# MCP Server Configuration
# Defines startup commands, environment requirements, and health monitoring for MCP servers

servers:
  fetch_server:
    name: "fetch_server"
    description: "MCP server for web content fetching"
    type: "python"
    command: "uvx mcp-server-fetch"
    python_version: "3.11"
    environment:
      PATH: "/home/luke/.local/bin:$PATH"
      PYTHONPATH: "/home/luke/.local/lib/python3.11/site-packages"
    health_check:
      enabled: true
      endpoint: "http://localhost:3001/health"
      timeout: 5
      interval: 30
    log_level: "INFO"
    restart_policy: "on-failure"
    max_restarts: 3
    
  puppeteer_server:
    name: "puppeteer_server"
    description: "MCP server for browser automation via Puppeteer"
    type: "nodejs"
    command: "npx @modelcontextprotocol/server-puppeteer"
    node_version: "20.18.1"
    environment:
      PATH: "/home/luke/.nvm/versions/node/v20.18.1/bin:$PATH"
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      NODE_ENV: "production"
    health_check:
      enabled: true
      endpoint: "http://localhost:3002/health"
      timeout: 10
      interval: 30
    log_level: "INFO"
    restart_policy: "on-failure"
    max_restarts: 3
    
  python_code_assistant:
    name: "python_code_assistant"
    description: "MCP server for Python code analysis and modification"
    type: "nodejs"
    command: "node /home/luke/Documents/Cline/MCP/python-code-assistant/build/index.js"
    node_version: "20.18.1"
    environment:
      PATH: "/home/luke/.nvm/versions/node/v20.18.1/bin:$PATH"
      NODE_ENV: "production"
    health_check:
      enabled: false  # Uses stdio transport, no HTTP endpoint
      timeout: 5
      interval: 60
    log_level: "INFO" 
    restart_policy: "on-failure"
    max_restarts: 5

# Global MCP server settings
global:
  startup_timeout: 30
  shutdown_timeout: 10
  log_directory: "logs/mcp"
  enable_monitoring: true
  monitoring_interval: 60